### GET users
GET http://localhost:3000/users

### DELETE USER
DELETE http://localhost:3000/users/5

### ADD USER
POST http://localhost:3000/users/
Content-Type: application/json

{
    "username":"admin",
    "password": "f5bd2911609a9515c25a2d0cf601453b0929e06edbb5d16e3c6eeb8f3bdda54c"
}
### LOGIN USER
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username":"admin",
    "password": "f5bd2911609a9515c25a2d0cf601453b0929e06edbb5d16e3c6eeb8f3bdda54c"
}

### ADD PROJECT
POST http://localhost:3000/projects/add_project
Content-Type: application/json

{
    "title": "",
    "description": "",
    "image_key": "",
    "hidden": false,
    "customer_link": ""
}

### UPDATE PROJECT
PATCH http://localhost:3000/projects/update_project/78
Content-Type: application/json

{
    "title": "Title",
    "description": "Description3",
    "image_key": "",
    "customer_link": "link",
    "hidden": true
}

### GET PROJECTS
GET http://localhost:3000/projects/get_projects
Content-Type: application/json

{
    "title": "Title",
    "description": "Description3",
    "image_key": ""
}


### GET PROJECTS NON HIDDEN
GET http://localhost:3000/projects/get_projects_non_hidden
Content-Type: application/json

{

}


### DELETE PROJECT
DELETE  http://localhost:3000/projects/delete_project/115
